# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 208fffc2b0d226ea300a8b034f6b78e9d759013a6e7f08d27bdf739979eae26e0b493f6953647848def965bfbd4ba05aeb10d8b3614c52b35d0819872d2ec015

test:
  secret_key_base: 1163e5b9c98395e7701d362dce22c7437cac20b08c55397b79a581e990555390700b595d24815a5d5a19cd3011c0e32c27ca70355040145f0b8ef216b8b91488

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
